services:
  rabbitmq:
    container_name: rabbitmq
    build: ../scripts/docker/rabbitmq/
    ports:
      - 15672:15672
      - 15692:15692
      - 5672:5672
      - 5671:5671
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
