name: Markdown

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    name: Run Markdown linting
    runs-on: ubuntu-latest
    env:
      api-dir: ./
    steps:
      - uses: articulate/actions-markdownlint@v1
